<!-- SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.1 -->
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="MB.FramePacing.Capture.UnitTest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\data\csharp\MB.FramePacing.Data.csproj" />
    <ProjectReference Include="..\MB.FramePacing.Marker\MB.FramePacing.Marker.csproj" />
  </ItemGroup>
</Project>
