<!-- SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.1 -->
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$([MSBuild]::GetPathOfFileAbove('UnitTest.props', '$(MSBuildProjectDirectory)'))" />

  <ItemGroup>
    <ProjectReference Include="..\MB.FramePacing.MarkerDecoding.csproj" />
  </ItemGroup>
</Project>
