#!/usr/bin/env python3
"""Measure how precise camera capture is at each camera frame rate, on the simulated camera (VERY EXPERIMENTAL camera support).

Runs `mb-framepacing selftest --camera` once per camera rate against a simulated display and prints a Markdown table: whether every
presented frame was found and how far the measured display times are from the simulation. The simulated camera uses a fixed seed, so
the numbers are the same on every run. They come from the simulation only, not from real cameras.

    python tools/camera_rate_table.py                      # 60 Hz display, the default rates
    python tools/camera_rate_table.py --refresh 144 --rates 240,500,1000
    python tools/camera_rate_table.py --update-doc         # also replace the table in doc/camera.md

Rates that are exact multiples of the refresh rate stay locked in step with the simulated display and look better than a real camera
would, since real cameras drift against the display. The defaults therefore use rates that are not multiples.
"""

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECT = ROOT / "measure" / "app" / "FramePacing" / "FramePacing.csproj"
DOC = ROOT / "doc" / "camera.md"
BEGIN = "<!-- camera-rate-table: generated by tools/camera_rate_table.py -->"
END = "<!-- /camera-rate-table -->"
DEFAULT_RATES = "100,130,250,330,500,1000"

ERROR_LINE = re.compile(
    r"Display time error against the simulation: mean (?P<mean>[\d.]+) ms, p95 (?P<p95>[\d.]+) ms, max (?P<max>[\d.]+) ms "
    + r"\(camera period (?P<period>[\d.]+) ms, (?P<frames>\d+) frames\)"
)


@dataclass
class Result:
    fps: float
    passed: bool
    mean: float | None
    p95: float | None
    max: float | None
    period: float


def run(fps: float, refresh: float) -> Result:
    command = ["dotnet", "run", "-c", "Release", "--no-build", "--project", str(PROJECT), "--"]
    command += ["selftest", "--camera", "--fps", f"{fps:g}", "--refresh", f"{refresh:g}"]
    output = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, encoding="utf-8", errors="replace").stdout
    match = ERROR_LINE.search(output)
    passed = "PASS (camera" in re.sub(r"\s+", " ", output)
    if match is None:
        return Result(fps, passed, None, None, None, 1000.0 / fps)
    return Result(fps, passed, float(match["mean"]), float(match["p95"]), float(match["max"]), float(match["period"]))


def ms(value: float | None, frame_ms: float) -> str:
    """An error in ms and as a share of the frame time."""
    return "–" if value is None else f"{value:.1f} ms ({100 * value / frame_ms:.0f} %)"


def table(results: list[Result], refresh: float) -> str:
    frame_ms = 1000.0 / refresh
    lines = [
        f"| Camera (on {refresh:g} Hz) | × refresh | Camera period | All frames found | Mean error | P95 error | Max error |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in results:
        found = "yes" if r.passed else "**no**"
        errors = f"{ms(r.mean, frame_ms)} | {ms(r.p95, frame_ms)} | {ms(r.max, frame_ms)}"
        lines.append(f"| {r.fps:g} fps | {r.fps / refresh:.1f}× | {r.period:.1f} ms | {found} | {errors} |")
    return "\n".join(lines)


def update_doc(text: str) -> bool:
    doc = DOC.read_text(encoding="utf-8")
    start, end = doc.find(BEGIN), doc.find(END)
    if start < 0 or end < start:
        print(f"{DOC}: the markers {BEGIN} ... {END} are missing", file=sys.stderr)
        return False
    # The markers may sit inside a list item: indent the table like them
    indent = doc[doc.rfind("\n", 0, start) + 1 : start]
    body = "\n".join(indent + line for line in text.splitlines())
    _ = DOC.write_text(doc[: start + len(BEGIN)] + "\n\n" + body + "\n\n" + indent + doc[end:], encoding="utf-8", newline="\n")
    print(f"Updated {DOC.relative_to(ROOT)}; run 'npm run format' to align the table.", file=sys.stderr)
    return True


class Arguments(argparse.Namespace):
    """The parsed command line."""

    refresh: float = 60.0
    rates: str = DEFAULT_RATES
    update_doc: bool = False


def parse_args() -> Arguments:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    _ = parser.add_argument("--refresh", type=float, default=60.0, help="simulated display refresh rate in Hz (default 60)")
    _ = parser.add_argument("--rates", default=DEFAULT_RATES, help=f"comma separated camera rates (default {DEFAULT_RATES})")
    _ = parser.add_argument("--update-doc", action="store_true", help="replace the generated table in doc/camera.md")
    return parser.parse_args(namespace=Arguments())


def main() -> int:
    args = parse_args()
    refresh = args.refresh
    rates = [float(r) for r in args.rates.split(",") if r.strip()]

    _ = subprocess.run(["dotnet", "build", "-c", "Release", str(PROJECT), "-v", "q", "-nologo"], cwd=ROOT, check=True)
    results: list[Result] = []
    for fps in rates:
        print(f"camera {fps:g} fps on a {refresh:g} Hz display...", file=sys.stderr)
        results.append(run(fps, refresh))
    text = table(results, refresh)
    print(text)
    if args.update_doc and not update_doc(text):
        return 1
    return 0 if all(r.passed for r in results) else 1


if __name__ == "__main__":
    sys.exit(main())
