#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (C) 2026 Mana Battery ApS
# SPDX-License-Identifier: LicenseRef-PolyForm-Perimeter-1.0.1
"""Measure what the C++ SDK adds to an executable, and keep the table in sdk/cpp/README.md up to date.

Builds the size probes (sdk/cpp/tests/size: a baseline program and one that uses the core, the marker, and the marker and data
modules) with the compiler CMake finds, in Release and MinSizeRel, linked so that unused code is dropped, and reports each probe's size
minus the baseline's (stripped on Linux and macOS; without the PDB on Windows). The builds go in sdk/cpp/build/size.

  python tools/measure_sdk_size.py --toolchain msvc-x64                     # measure and print
  python tools/measure_sdk_size.py --toolchain msvc-x64 --check             # fail when the README's row is off by more than the tolerance
  python tools/measure_sdk_size.py --toolchain msvc-x64 --json size.json    # also write the measurement (CI uploads it)
  python tools/measure_sdk_size.py --update-doc size-*.json                 # rewrite the README's rows from measurements
  python tools/measure_sdk_size.py --toolchain msvc-x64 --update-doc        # measure, then rewrite this toolchain's rows

A row without numbers in the README (a toolchain not measured yet) is reported, not failed. On GitHub Actions the measurement also goes
into the job summary.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import cast

ROOT = Path(__file__).resolve().parent.parent
PROBE_DIR = ROOT / "sdk" / "cpp" / "tests" / "size"
README = ROOT / "sdk" / "cpp" / "README.md"
BUILD_DIR = ROOT / "sdk" / "cpp" / "build" / "size"
BEGIN = "<!-- sdk-size-table: generated by tools/measure_sdk_size.py -->"
END = "<!-- /sdk-size-table -->"

TOOLCHAINS = {
    "msvc-x64": "MSVC, Windows x64",
    "gcc-x64": "GCC, Linux x64",
    "clang-x64": "Clang, Linux x64",
    "appleclang-arm64": "AppleClang, macOS arm64",
}
BUILD_TYPES = ("Release", "MinSizeRel")
# Column key, probe target, column title
COLUMNS = (("core", "size_core", "Core"), ("marker", "size_marker", "Core + marker"), ("data", "size_marker_data", "Core + marker + data"))
BASELINE = "size_baseline"
HEADER = ("Toolchain", "Compiler", "Build", *(title for _, _, title in COLUMNS))
# A measurement is off when it differs from the README by more than the larger of these
TOLERANCE_FRACTION = 0.10
TOLERANCE_KIB = 4.0


class Arguments(argparse.Namespace):
    """The parsed command line."""

    toolchain: str | None = None
    check: bool = False
    json: str | None = None
    update_doc: list[str] | None = None


@dataclass
class Measurement:
    """One toolchain's sizes: KiB added per build type and column."""

    toolchain: str
    compiler: str
    sizes: dict[str, dict[str, float]]

    def to_json(self) -> dict[str, object]:
        return {"toolchain": self.toolchain, "compiler": self.compiler, "sizes": self.sizes}

    @staticmethod
    def from_json(data: object) -> "Measurement":
        record = cast(dict[str, object], data) if isinstance(data, dict) else {}
        sizes = record.get("sizes")
        if not isinstance(sizes, dict):
            raise ValueError("a measurement is an object with 'sizes'")
        parsed: dict[str, dict[str, float]] = {}
        for build_type in BUILD_TYPES:
            columns = cast(dict[str, object], sizes).get(build_type)
            if not isinstance(columns, dict):
                raise ValueError(f"the measurement has no {build_type} sizes")
            parsed[build_type] = {key: float(cast(float, cast(dict[str, object], columns)[key])) for key, _, _ in COLUMNS}
        return Measurement(str(record["toolchain"]), str(record["compiler"]), parsed)


def run(command: list[str], cwd: Path | None = None) -> None:
    print("> " + " ".join(command), flush=True)
    _ = subprocess.run(command, check=True, cwd=cwd)


def find_executable(build: Path, build_type: str, name: str) -> Path:
    for candidate in (build / build_type / f"{name}.exe", build / f"{name}.exe", build / name):
        if candidate.is_file():
            return candidate
    sys.exit(f"{name} was not built in {build}")


def stripped_size(executable: Path, work: Path) -> int:
    """The executable's size without its symbols: on Windows the symbols are in the PDB already."""
    if sys.platform == "win32":
        return executable.stat().st_size
    copy = work / f"{executable.name}.stripped"
    _ = shutil.copyfile(executable, copy)
    run(["strip", str(copy)])
    return copy.stat().st_size


def compiler_name(build: Path) -> str:
    for path in (build / "CMakeFiles").glob("*/CMakeCXXCompiler.cmake"):
        text = path.read_text(encoding="utf-8")
        compiler = re.search(r'set\(CMAKE_CXX_COMPILER_ID "([^"]*)"\)', text)
        version = re.search(r'set\(CMAKE_CXX_COMPILER_VERSION "([^"]*)"\)', text)
        if compiler and version:
            return f"{compiler.group(1)} {version.group(1)}"
    return "unknown"


def measure(toolchain: str) -> Measurement:
    sizes: dict[str, dict[str, float]] = {}
    compiler = "unknown"
    # Next to the presets' builds (ignored by git), kept between runs; stripped copies go in a temporary folder
    with tempfile.TemporaryDirectory(prefix="mb-framepacing-size-") as temporary:
        work = Path(temporary)
        for build_type in BUILD_TYPES:
            build = BUILD_DIR / build_type
            run(["cmake", "-S", str(PROBE_DIR), "-B", str(build), f"-DCMAKE_BUILD_TYPE={build_type}"])
            targets = [BASELINE, *(target for _, target, _ in COLUMNS)]
            run(["cmake", "--build", str(build), "--config", build_type, "--parallel", "--target", *targets])
            compiler = compiler_name(build)
            baseline = stripped_size(find_executable(build, build_type, BASELINE), work)
            sizes[build_type] = {
                key: round((stripped_size(find_executable(build, build_type, target), work) - baseline) / 1024.0, 1) for key, target, _ in COLUMNS
            }
    return Measurement(toolchain, compiler, sizes)


def format_kib(value: float | None) -> str:
    return "-" if value is None else f"{value:.1f} KiB"


def parse_kib(text: str) -> float | None:
    match = re.fullmatch(r"(-?\d+(?:\.\d+)?) KiB", text.strip())
    return float(match.group(1)) if match else None


Row = tuple[str, str, str, list[float | None]]


def read_table(readme: str) -> dict[tuple[str, str], Row]:
    """The README's rows by (toolchain id, build type)."""
    begin = readme.index(BEGIN)
    end = readme.index(END, begin)
    labels = {label: key for key, label in TOOLCHAINS.items()}
    rows: dict[tuple[str, str], Row] = {}
    for line in readme[begin:end].splitlines():
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) != len(HEADER) or cells[0] not in labels:
            continue
        rows[(labels[cells[0]], cells[2])] = (cells[0], cells[1], cells[2], [parse_kib(cell) for cell in cells[3:]])
    return rows


def render_table(rows: dict[tuple[str, str], Row]) -> str:
    """The table as Prettier writes it: padded cells, the size columns right aligned."""
    lines: list[list[str]] = [list(HEADER)]
    for toolchain, label in TOOLCHAINS.items():
        for build_type in BUILD_TYPES:
            _, compiler, _, values = rows.get((toolchain, build_type), (label, "-", build_type, [None] * len(COLUMNS)))
            lines.append([label, compiler, build_type, *(format_kib(value) for value in values)])
    widths = [max(3, *(len(line[column]) for line in lines)) for column in range(len(HEADER))]
    right = [False, False, False, *([True] * len(COLUMNS))]

    def cell(text: str, column: int) -> str:
        return text.rjust(widths[column]) if right[column] else text.ljust(widths[column])

    out = ["| " + " | ".join(cell(text, column) for column, text in enumerate(lines[0])) + " |"]
    out.append("| " + " | ".join(("-" * (widths[column] - 1) + ":") if right[column] else "-" * widths[column] for column in range(len(HEADER))) + " |")
    out.extend("| " + " | ".join(cell(text, column) for column, text in enumerate(line)) + " |" for line in lines[1:])
    return "\n".join(out)


def update_doc(measurements: list[Measurement]) -> None:
    readme = README.read_text(encoding="utf-8")
    rows = read_table(readme)
    for measurement in measurements:
        label = TOOLCHAINS[measurement.toolchain]
        for build_type in BUILD_TYPES:
            values: list[float | None] = [measurement.sizes[build_type][key] for key, _, _ in COLUMNS]
            rows[(measurement.toolchain, build_type)] = (label, measurement.compiler, build_type, values)
    begin = readme.index(BEGIN) + len(BEGIN)
    end = readme.index(END, begin)
    _ = README.write_text(readme[:begin] + "\n\n" + render_table(rows) + "\n\n" + readme[end:], encoding="utf-8", newline="\n")
    print(f"Updated {README.relative_to(ROOT).as_posix()}")


def check(measurement: Measurement) -> bool:
    rows = read_table(README.read_text(encoding="utf-8"))
    ok = True
    for build_type in BUILD_TYPES:
        row = rows.get((measurement.toolchain, build_type))
        for index, (key, _, title) in enumerate(COLUMNS):
            measured = measurement.sizes[build_type][key]
            documented = row[3][index] if row else None
            where = f"{TOOLCHAINS[measurement.toolchain]} {build_type} {title}"
            if documented is None:
                annotate("warning", f"{where}: the README has no number yet (measured {format_kib(measured)})")
                continue
            if abs(measured - documented) > max(TOLERANCE_FRACTION * abs(documented), TOLERANCE_KIB):
                annotate("error", f"{where}: measured {format_kib(measured)}, the README says {format_kib(documented)}")
                ok = False
    if not ok:
        print(f"Regenerate the table: python tools/measure_sdk_size.py --toolchain {measurement.toolchain} --update-doc (or from CI's measurements)")
    return ok


def annotate(level: str, message: str) -> None:
    print(f"::{level}::{message}" if os.environ.get("GITHUB_ACTIONS") else f"{level}: {message}", flush=True)


def write_summary(measurement: Measurement) -> None:
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary:
        return
    label = TOOLCHAINS[measurement.toolchain]
    rows: dict[tuple[str, str], Row] = {
        (measurement.toolchain, build_type): (label, measurement.compiler, build_type, [measurement.sizes[build_type][key] for key, _, _ in COLUMNS])
        for build_type in BUILD_TYPES
    }
    table = "\n".join(line for line in render_table(rows).splitlines() if label in line or line.startswith(("| Toolchain", "| ---")))
    with open(summary, "a", encoding="utf-8") as stream:
        _ = stream.write(f"### What the C++ SDK adds to an executable ({label})\n\n{table}\n")


def parse_args() -> Arguments:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    _ = parser.add_argument("--toolchain", choices=list(TOOLCHAINS), help="measure with the compiler CMake finds, labelled as this toolchain")
    _ = parser.add_argument("--check", action="store_true", help="fail when the README's rows for --toolchain are off by more than the tolerance")
    _ = parser.add_argument("--json", help="write the measurement to this file")
    _ = parser.add_argument("--update-doc", nargs="*", metavar="RESULT", help="rewrite the README's rows (from these measurement files and/or --toolchain)")
    return parser.parse_args(namespace=Arguments())


def main() -> int:
    args = parse_args()
    if args.toolchain is None and not args.update_doc:
        print("Nothing to do: give --toolchain to measure, or --update-doc with measurement files")
        return 2
    measurements = [Measurement.from_json(cast(object, json.loads(Path(path).read_text(encoding="utf-8")))) for path in args.update_doc or []]
    ok = True
    if args.toolchain is not None:
        measurement = measure(args.toolchain)
        print(json.dumps(measurement.to_json(), indent=2))
        if args.json:
            _ = Path(args.json).write_text(json.dumps(measurement.to_json(), indent=2) + "\n", encoding="utf-8")
        write_summary(measurement)
        if args.check:
            ok = check(measurement)
        measurements.append(measurement)
    if args.update_doc is not None:
        update_doc(measurements)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
